=== lombold/translation-typing/src/assets/i18n/translations-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "USED_KEY": {
      "type": "string"
    },
    "UNUSED_KEY": {
      "type": "string"
    },
    "ENUM_KEY_dog": {
      "type": "string"
    },
    "ENUM_KEY_cat": {
      "type": "string"
    },
    "ENUM_KEY_mouse": {
      "type": "string"
    },
    "OBJECT_KEY": {
      "type": "object",
      "properties": {
        "USED_KEY": {
          "type": "string"
        },
        "UNUSED_KEY": {
          "type": "string"
        }
      },
      "required": [
        "USED_KEY",
        "UNUSED_KEY"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "$schema",
    "USED_KEY",
    "ENUM_KEY_dog",
    "ENUM_KEY_cat",
    "ENUM_KEY_mouse",
    "OBJECT_KEY"
  ],
  "additionalProperties": false
}

=== lombold/translation-typing/src/assets/i18n/de.json
{
  "$schema": "translations-schema.json",
  "USED_KEY": "Das ist ein gebrauchter Schl端ssel",
  "UNUSED_KEY": "Das ist ein unbenutzter Schl端ssel",
  "ENUM_KEY_dog": "Hund",
  "ENUM_KEY_cat": "Katze",
  "ENUM_KEY_mouse": "Maus",
  "OBJECT_KEY": {
    "USED_KEY": "Das ist ein gebrauchter Schl端ssel",
    "UNUSED_KEY": "Das ist ein unbenutzter Schl端ssel"
  }
}
